FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --default-timeout=300 \
    -i https://pypi.org/simple \
    -r requirements.txt

COPY . .

# Worker does NOT expose any ports
CMD ["rq", "worker", "--url", "redis://redis:6379", "--with-scheduler"]
